server:
  port: 10010

spring:
  data:
    mongodb:
      uri: mongodb://kuro:blacksheepwall@localhost:27017/themis
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy